# -*- coding: utf-8 -*-
{
    "name": "marketing_eyetracking",
    "version": "1.0",
    "summary": "Analyze marketing campaigns using eye tracking techniques",
    "description": """This module allows recording and analyzing eye tracking data during marketing campaigns.
    Additionally, it integrates a webcam functionality to capture live video.""",
    "author": "Eduardo Robles Russo",
    "category": "Marketing",
    "depends": ["base", "web"],
    "data": [
        "security/ir.model.access.csv",
        "views/analysis_views.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "https://www.googletagmanager.com/gtag/js?id=G-0FG0LDC7C0",
            "marketing_eyetracking/static/src/js/google_analytics_config.js",
        ],
        "web.assets_backend": [
            "marketing_eyetracking/static/src/lib/bootstrap.bundle.min.js",
            "marketing_eyetracking/static/src/lib/d3.v3.min.js",
            "marketing_eyetracking/static/src/lib/localforage.js",
            "marketing_eyetracking/static/src/lib/webgazer.js",
            "marketing_eyetracking/static/src/lib/sweetalert.min.js",
            "marketing_eyetracking/static/src/lib/html2canvas.min.js",
            "marketing_eyetracking/static/src/js/calibration.js",
            "marketing_eyetracking/static/src/js/main.js",
            "marketing_eyetracking/static/src/js/precision_store_points.js",
            "marketing_eyetracking/static/src/js/precision_calculation.js",
            "marketing_eyetracking/static/src/js/resize_canvas.js",
            "marketing_eyetracking/static/src/js/eye_tracking_component.js",
            "marketing_eyetracking/static/src/js/web_dialog_client_action.js",
            "marketing_eyetracking/static/src/js/google_analitics.js",
            "https://www.googletagmanager.com/gtag/js?id=G-0FG0LDC7C0",
            "marketing_eyetracking/static/src/xml/eye_tracking_component.xml",
            "marketing_eyetracking/static/src/xml/web_dialog_client_action.xml",
            "marketing_eyetracking/static/src/xml/chart-graphics/chart/chart_renderer.js",
            "marketing_eyetracking/static/src/xml/chart-graphics/chart/chart_renderer.xml",
            "marketing_eyetracking/static/src/xml/chart-graphics/greet_dashboard.js",
            "marketing_eyetracking/static/src/xml/chart-graphics/greet_dashboard.xml",
        ],
    },
    "installable": True,
    "application": True,
}
